### ISSUE TITLE
Style indent value not read from python dict

### ISSUE THREAD

**Issue by charlielewisme** [largecats/hiveql-formatter#72]
- when setting "indent" using STYLE dict, `_create_style_from_dict()` throws error
- underlying cause is `ast.literal_eval` failing to parse whitespace strings
- this behaviour is noted here: https://bugs.python.org/issue41887

Current workaround:
- clone the STYLE dict
- pop "indent"
- parse STYLE to create Style() object
- then set the "indent" key
```
from sparksqlformatter import api as ssf

STYLE = {
    "indent": "  "
}

new_style = STYLE
indent = new_style.pop("indent")
FIXED_STYLE = ssf._create_style_from_dict(new_style)
FIXED_STYLE.indent = indent

sql = "SELECT * FROM my_tbl"
formatted_sql = ssf.format_query(query=sql, style=FIXED_STYLE)
```

**Comment by largecats** [comment]
Thank you for the catch. Updated logic to not parse value through `ast.liateral_eval` if key is `"indent"`. Kindly verify.

**Comment by charlielewisme** [comment]
No problem, I'll take a look.

**Comment by charlielewisme** [comment]
I think that should work just fine!
